name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'test'
        type: choice
        options:
          - 'test'
          - 'production'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for proper versioning with setuptools_scm
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        # Create virtual environment and install dependencies
        uv venv
        uv pip install build twine
    
    - name: Build package
      run: |
        uv run -m build
    
    - name: Publish to Test PyPI
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.release_type == 'test'
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: |
        uv run -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
    
    - name: Publish to PyPI (from workflow dispatch)
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.release_type == 'production'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        uv run -m twine upload dist/*
    
    - name: Publish to PyPI (from tag)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        uv run -m twine upload dist/*